steps:
  - name : 'python:3.15-rc-alpine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Starting Python hello.py ==="
        python hello.py
        echo "=== Finished hello.py ==="

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '10s'
